defaults: &defaults
  adapter: postgresql
  host: localhost
  port: 5432
  username: pguser
  password: 
  database: link_save_service
  schema_search_path: public
  encoding: utf8
  template: template1

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
